### ISSUE TITLE
Gradients

### ISSUE THREAD

**Issue by ThibaultLemaire** [Weasy666/bevy_svg#27] opened 2023-02-16 19:59 UTC
Hi!

I would like to render SVGs with gradients, which is currently unsupported (#8).

However my gradients are simple linear gradients, and I could probably implement them with simple shaders, but I don't see any method to pass a custom material to an `Svg3dBundle`.

I'm a total newb to bevy (started learning this weekend) but looking at your code, I was thinking maybe I could specialize your specialized pipeline? Do you reckon that would be a solution? Or is this a stupid idea?

**Comment by Weasy666** [comment] 2023-02-26 15:05
Hi!

The code is currently only aware of simple fill colors, see https://github.com/Weasy666/bevy_svg/blob/03a273cde9b239faec34a8abd840f9f750a14904/src/svg.rs#L51, and ignores all other kinds of fills, like `LinearGradient`, `RadialGradient` and `Pattern`. In that match, the `usvg` types are converted to `Lyon` types or `bevy_svg` types that use `Lyon` types.

In the next step, those descriptors are then passed to `lyon_tesselation` to generate the colored vertices needed to render those paths, see here https://github.com/Weasy666/bevy_svg/blob/03a273cde9b239faec34a8abd840f9f750a14904/src/render/tessellation.rs#L34.

If lyon is able to handle gradients, then you would "just" need to somehow convert the `usvg` types to the types `Lyon` expects and it could probably work.

And i am really sorry for the late answer, hope it is not too late and was kind of helpful 🙂

**Comment by Weasy666** [comment] 2023-11-03 07:48
I'll close this, as it is a duplicate of #8

**Closed by Weasy666** 2023-11-03 07:48 UTC
